baseurl             = "https://skrilltrax.dev/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Aditya Wasan"
title               = "Aditya Wasan"
pygmentsuseclasses  = true
# disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
# googleAnalytics     = "UA-123-45"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Code"
weight                 = -100
identifier             = "code"
url                    = "/code/"

[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
showlatestpostsheader  = false			       # show latest posts header or not 
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Aditya Wasan"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
email                  = "hey@skrilltrax.dev"
# extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
# faviconfile            = "img/leaf.ico"
github                 = "//github.com/skrilltrax"
instagram              = "//instagram.com/skrilltrax"
# px500                  = "//500px.com/username"
lang                   = "en"
linkedin               = "//linkedin.com/in/skrilltrax"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
# selfintro              = "Hi, I'm an android developer and I love kotlin."
twitter                = "//twitter.com/skrilltrax"
# mastodon               = "//example.com/@you"
telegram               = "//t.me/skrilltrax"

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik

gitalk                 = false
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
gitalk_clientID        = "your client id"
gitalk_clientSecret    = "your client secret"
gitalk_repo            = "your repo url"
gitalk_owner           = "the owner of this repo"
gitalk_admin           = ['a', 'list', 'of', 'administrator']

# avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
# gatracker              = "XYZ" # use googleAnalytics instead
# initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.

