# OVERRIDE #

languageCode = "en-us"
title = "Codex"
baseURL = "https://example.org/"
copyright = "© {year}"

[params]

  name = "Codex"
  description = "A minimal blog theme for hugo."
  twitter = "hugo-theme-codex"
  github = "jakewies/hugo-theme-codex"

# OVERRIDE #

# DONT OVERRIDE #

preserveTaxonomyNames = true

[[menu.main]]
    identifier = "about"
    name = "about"
    url = "/"

[taxonomies]
  tag = "tags"

# DONT OVERRIDE #
